---
- hosts: all
  gather_facts: false
  tasks:
    - name: Update packages
      become: yes
      yum:
        name: "*"
        state: latest
    - name: Install Java 11
      become: yes
      command: amazon-linux-extras install java-openjdk11 -y
    - name: Download Jenkins repo
      become: yes
      get_url:
        url: https://pkg.jenkins.io/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name: Import key file from Jenkins-CI to enable the installation
      become: yes
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    - name:  Install Jenkins
      become: yes
      yum:
        name: jenkins
        state: latest
    - name: Start Jenkins server
      become: yes
      systemd:
        name: jenkins
        state: started
    - name: Get Ansible Admin password
      become: yes
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: admin_password
    - debug:
        var: admin_password.stdout_lines
